databases:
  - name: kiyo-Attendance-System_B
    databaseName: kiyo-Attendance-System_B
    user: Kiyotoshi Ohara
    region: singapore

services:
  - type: web
    name: kiyo-Attendance-System_B
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgres://kiyo_datebase3588_user:orED5PYCdjAfnNM9DCIkzUphefCkepU3@dpg-ci94h0dph6ekmcics5ig-a.singapore-postgres.render.com/kiyo_datebase3588
        fromDatabase:
          name: kiyo-Attendance-System_B
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false